apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot-failure-2
spec:
  template:
    spec:
      containers:
        - name: kuard
          image: luizgustavoou/kuard:latest
          imagePullPolicy: Always
          command:
            - "/kuard"
          args:
            - "--keygen-enable"
            - "--keygen-exit-on-complete"
            - "--keygen-exit-code=1"
            - "--keygen-num-to-gen=3"
      restartPolicy: Never
