apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver # Label do ReplicaSet
spec:
  selector:
    matchLabels:
      app: goserver # Critério de seleção dos Pods
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver" # Label dos Pods
    spec:
      containers:
        - name: "goserver"
          image: "luizgustavoou/hello-go:v5.2"
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 30 
          
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3 # A cada 3 segundos verifica a saúde
            failureThreshold: 1 # Após 1 falha, o Pod será reiniciado
            timeoutSeconds: 1 # Timeout de 1 segundo para a verificação
            successThreshold: 1 # Após 1 sucesso, o Pod é considerado saudável
            # initialDelaySeconds: 10 # Aguarda 10 segundos antes de iniciar as verificações
          
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5 # A cada 5 segundos verifica a saúde
            failureThreshold: 1 # Após 1 falha, o Pod será reiniciado
            timeoutSeconds: 1 # Timeout de 1 segundo para a verificação
            successThreshold: 1 # Após 1 sucesso, o Pod é considerado saudável
            # initialDelaySeconds: 15 # Aguarda 10 segundos antes de iniciar as verificações

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: /go/myfamily
              name: config
      volumes:
        - name: config  
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt