apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver # Label do ReplicaSet
spec:
  selector:
    matchLabels:
      app: goserver # Critério de seleção dos Pods
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver" # Label dos Pods
    spec:
      containers:
        - name: "goserver"
          image: "luizgustavoou/hello-go:v5"
          envFrom:
            - configMapRef:
                name: goserver-env
          volumeMounts:
            - mountPath: /go/myfamily
              name: config
      volumes:
        - name: config  
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt