apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: fullcycle.duckdns.org
      http:
        paths:
          - path: /nodered
            pathType: Prefix 
            backend:
              service:
                name: nodered-service
                port:
                  number: 80

          - path: /goserver
            pathType: Prefix
            backend:
              service:
                name: goserver-service
                port:
                  number: 80
    - host: alpaca.example.com
      http:
        paths:
          - backend:
              service:
                name: goserver-service
                port:
                  number: 80
            path: /
            pathType: Prefix
        
  tls:
    - hosts:
        - fullcycle.duckdns.org
      secretName: letsencrypt-tls
