apiVersion: v1
kind: Pod
metadata:
  name: kuar-pod
  labels:
    app: kuar
spec:
  containers:
    - name: kuar-container
      image: luizgustavoou/kuard:latest
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
