apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nodered-settings
data:
  settings.js: |
    module.exports = {
      // Base path do Node-RED (editor + http endpoints)
      httpRoot: "/nodered",

      // (opcional) se quiser expor apenas o editor em /nodered
      // httpAdminRoot: "/nodered",

      // Porta padrão do Node-RED
      uiPort: process.env.PORT || 1880,

      // Permitir servir arquivos estáticos corretamente
      // httpStatic: '/data/public',

      adminAuth: {
        type: "credentials",
        users: [{
          username: "admin",
          password: "$2b$08$OvNjnbFgmafKTq26k2d./eKnXM.DtkP1aUt0Q8UoaoI2lBSGExAgy",
          permissions: "*"
        }]
      },
      editorTheme: {
        page: {
          title: "Node-RED"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: nodered
          image: nodered/node-red:3.1.9
          env:
            - name: NODE_RED_ENABLE_PROJECTS
              value: "false"
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 256Mi
          ports:
            - containerPort: 1880
          volumeMounts:
            - name: nodered-storage
              mountPath: /data
            - name: nodered-settings
              mountPath: /data/settings.js
              subPath: settings.js
      volumes:
        - name: nodered-storage
          persistentVolumeClaim:
            claimName: nodered-pvc
        - name: nodered-settings
          configMap:
            name: nodered-settings
        
---
apiVersion: v1
kind: Service
metadata:
  name: nodered-service
spec:
  type: ClusterIP
  selector:
    app: nodered
  ports:
    - port: 80
      targetPort: 1880
      protocol: TCP
