apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
  labels:
    app: goserver # Label do ReplicaSet
spec:
  selector:
    matchLabels:
      app: goserver # Critério de seleção dos Pods
  replicas: 10
  template:
    metadata:
      labels:
        app: "goserver" # Label dos Pods
    spec:
      containers:
        - name: "goserver"
          image: "luizgustavoou/hello-go:v2"