apiVersion: v1
kind: Service
metadata:
  name: goserver-service-nodeport
spec:
  type: NodePort
  selector:
    app: goserver
  ports:
  - name: goserver-service-nodeport
    port: 80
    targetPort: 8000
    protocol: TCP
    nodePort: 30001

