apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: logging
data:
  fluent-bit.yaml: |
    service:
      flush: 5
      log_level: info
      parsers_file: parsers.yaml

    pipeline:
      inputs:
        - name: tail
          path: /var/log/containers/*.log
          parser: docker
          tag: kube.*
      
      filters:
        - name: kubernetes
          match: kube.*
          kube_tag_prefix: kube.var.log.containers.
      
      outputs:
        - name: es
          match: "*"
          host: elasticsearch-h.logging.svc.cluster.local
          port: 9200
          index: kubernetes-logs
          type: _doc
          suppress_type_name: true

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
      annotations:
        checksum/config: "v2"
    spec:
      serviceAccountName: fluentbit
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        # - name: varlibdockercontainers
        #   hostPath:
        #     path: /var/lib/docker/containers
        - name: fluentbit-config
          configMap:
            name: fluentbit-config
      containers:
        - name: fluentbit
          image: fluent/fluent-bit:2.2
          args:
            - -c
            - /fluent-bit/etc/fluent-bit.yaml
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            # - name: varlibdockercontainers
            #   mountPath: /var/lib/docker/containers
            #   readOnly: true
            - name: fluentbit-config
              mountPath: /fluent-bit/etc/fluent-bit.yaml
              subPath: fluent-bit.yaml
